name: Traffic Archive

on:
  schedule:
    - cron: '0 0 * * *' # Laeuft jeden Tag um Mitternacht
  workflow_dispatch:      # Ermoeglicht manuelles Starten

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Archive Traffic
        uses: enricomarino/traffic-log@master
        with:
          # Achte darauf, dass der Name hier exakt deinem Secret entspricht!
          token: ${{ secrets.GHTRAFFICToken }}
