name: Traffic Archive

on:
  schedule:
    - cron: '0 0 * * *' # Laeuft jeden Tag um Mitternacht
  workflow_dispatch:      # Erlaubt es, den Prozess manuell zu starten

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitHub Traffic Archive
        uses: sangonzalezplus/github-traffic-archiver@ master
        env:
          PAT: ${{ secrets.TRAFFIC_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
