name: Traffic Archive

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  run-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitHub Traffic Stats
        uses: tech-mark0/github-traffic-stats@master
        with:
          # Dein Token aus den Secrets
          token: ${{ secrets.GHTRAFFICToken }}
          # Das Repository, das analysiert werden soll (Format: Besitzer/Name)
          repository: ${{ github.repository }}
